const menuData = [
 {category:"Snacks", name:"Onion Pakoda", price:125, img:"onionpakoda.jpg"},
  {category:"Snacks", name:"Chicken Pakoda", price:220, img:"chickenpakoda.jpg"},
  {category:"Snacks", name:"Paneer Pakoda", price:160, img:"paneerpakoda.webp"},
  {category:"Snacks", name:"Onion Bajji", price:100, img:"onionbajji.jpg"},
  {category:"Snacks", name:"Potato Bajji", price:100, img:"potatobajji.jpg"},
  {category:"Snacks", name:"Chicken Nuggets", price:190, img:"chickennuggets.avif"},
  {category:"Snacks", name:"Veg Nuggets", price:120, img:"vegnuggets.webp"},
  {category:"Snacks", name:"Chicken Spring Roll", price:200, img:"chickenspringroll.jpg"},
  {category:"Snacks", name:"Veg Cutlet", price:150, img:"vegcutlet.jpg"},
  {category:"Snacks", name:"Fish Cutlet", price:180, img:"fishcutlet.png"},
  {category:"Snacks", name:"Meat Cutlet", price:200, img:"meatcutlet.jpg"},
  {category:"Snacks", name:"Veg Samosa", price:140, img:"vegsamoosa.jpg"},
  {category:"Snacks", name:"Chicken Samosa", price:200, img:"chickensamoosa.webp"},
  {category:"Snacks", name:"Veg Momos", price:120, img:"vegmomos.webp"},
  {category:"Snacks", name:"Chicken Momos", price:160, img:"chickenmomos.png"},
  {category:"Snacks", name:"Prawns Momos", price:190, img:"prawnsmomos.webp"},
  {category:"Snacks", name:"French Fries", price:120, img:"frenchfries.avif"},
  {category:"Snacks", name:"Potato Wedges (Herbed)", price:120, img:"potatowedges.jpg"},
  {category:"Snacks", name:"Fish Fingers", price:350, img:"fishfingers.webp"},
 


{category:"Soups", name:"Veg Clear Soup", price:120, img:"vegclearsoup.jpg"},
{category:"Soups", name:"Chicken Clear Soup", price:120, img:"chickenclearsoup.webp"},
{category:"Soups", name:"Veg Mancho Soup", price:100, img:"manchowsoup.jpg"},
{category:"Soups", name:"Chicken Manchoue", price:150, img:"chickenmanchow.jpg"},
{category:"Soups", name:"Hot And Sour Veg", price:100, img:"hotandsoursoup.jpg"},
{category:"Soups", name:"Hot And Sour Non Veg", price:125, img:"hotandsourchicken.jpg"},
{category:"Soups", name:"Veg Sweet Corn", price:120, img:"cornsoup.png"},
{category:"Soups", name:"Non Veg Sweet Corn", price:125, img:"nonvegsweetcorn.jpg"},
{category:"Soups", name:"Lemon Corriender Veg", price:120, img:"lemoncorrienderveg.jpg"},
{category:"Soups", name:"Mushroom Soup", price:110, img:"mushroom.jpg"},
{category:"Soups", name:"Cream Of Chicken", price:150, img:"creamofchicken.jpg"},
{category:"Soups", name:"Cream Of Veg", price:120, img:"creamofveg.png"},
{category:"Soups", name:"Cream Of Mushroom", price:120, img:"creamofmushroom.webp"},
{category:"Soups", name:"Cream Of Tomato", price:120, img:"creamoftomato.webp"},


{category:"Sandwich", name:"Zacs Nonveg Club Sandwich", price:200, img:"nonvegclubsandwitch.jpg"},
{category:"Sandwich", name:"Zacs Veg Club Sandwich", price:150, img:"vegclubsandwitch.webp"},
{category:"Sandwich", name:"Veg Sandwich", price:100, img:"vegsandwich.jpg"},
{category:"Sandwich", name:"Chicken Sandwich", price:150, img:"chickensandwich.jpg"},



{category:"Starters Non-Veg", name:"Beef Chukka", price:350, img:"beefchukka.webp"},
{category:"Starters Non-Veg", name:"Chilly Beef", price:350, img:"chillibeef.webp"},
{category:"Starters Non-Veg", name:"Beef Dry Fry (Kerala Style)", price:370, img:"beefdryfry.png"},
{category:"Starters Non-Veg", name:"Dragon Beef", price:380, img:"dragonbeef.png"},
{category:"Starters Non-Veg", name:"Beef With Veg Dry", price:340, img:"beefwithvegdry.png"},
{category:"Starters Non-Veg", name:"Korean Beef", price:410, img:"koreanbeef.jpg"},
{category:"Starters Non-Veg", name:"Beef Vartu", price:370, img:"beefvarattu.png"},
{category:"Starters Non-Veg", name:"Garlic Beef", price:380, img:"garlicbeef.webp"},
{category:"Starters Non-Veg", name:"Chicken 65", price:280, img:"chicken65.jpg"},
{category:"Starters Non-Veg", name:"Chicken Lolipop", price:280, img:"chickenlolippop.jpg"},
{category:"Starters Non-Veg", name:"Chicken Chukka", price:300, img:"chickenchukka.webp"},
{category:"Starters Non-Veg", name:"Chicken Pallipalayam", price:300, img:"chickenpallipayam.webp"},
{category:"Starters Non-Veg", name:"Chicken Pepper Fry", price:300, img:"chickenpepperfry.webp"},
{category:"Starters Non-Veg", name:"Ginger Chicken", price:230, img:"gingerchicken.jpg"},
{category:"Starters Non-Veg", name:"Ginger Beef", price:380, img:"ginger-beef.webp"},
{category:"Starters Non-Veg", name:"Nattu Kozhi Varuval", price:450, img:"nattu-kozhi-varuval.webp"},
{category:"Starters Non-Veg", name:"Dragon Chicken", price:300, img:"dragon-chicken.png"},
{category:"Starters Non-Veg", name:"Korean Chicken", price:320, img:"korean-chicken.jpg"},
{category:"Starters Non-Veg", name:"Fish 65", price:350, img:"fish-65.webp"},
{category:"Starters Non-Veg", name:"Butterfly Shrimp", price:380, img:"butterfly-shrimp.webp"},
{category:"Starters Non-Veg", name:"Prawns 65", price:350, img:"prawns-65.jpg"},
{category:"Starters Non-Veg", name:"Ginger Fish", price:300, img:"ginger-fish.jpg"},
{category:"Starters Non-Veg", name:"Mutton Chukka", price:400, img:"mutton-chukka.jpg"},
{category:"Starters Non-Veg", name:"Kerala Prawn Varatiyathu", price:410, img:"kerala-prawn-varatiyathu.jpg"},
{category:"Starters Non-Veg", name:"Kerala Fish Pollichathu", price:430, img:"kerala-fish-pollichathu.avif"},
{category:"Starters Non-Veg", name:"Prawns Dry Fry", price:330, img:"prawns-dry-fry.webp"},
{category:"Starters Non-Veg", name:"Chilly Chicken Dry", price:230, img:"chilly-chicken-dry.avif"},
{category:"Starters Non-Veg", name:"Chilly Fish Dry", price:350, img:"chilly-fish-dry.jpg"},
{category:"Starters Non-Veg", name:"Chilly Egg", price:200, img:"chilly-egg.png"},
{category:"Starters Non-Veg", name:"Crab Lolipop", price:300, img:"crab-lolipop.jpeg"},


{category:"Starters Veg", name:"Gobi 65", price:175, img:"gobi-65.png"},
{category:"Starters Veg", name:"Chilly Gobi", price:230, img:"chilly-gobi.png"},
{category:"Starters Veg", name:"Mushroom 65", price:175, img:"mushroom-65.png"},
{category:"Starters Veg", name:"Paneer 65", price:250, img:"paneer-65.png"},
{category:"Starters Veg", name:"Chilly Paneer", price:250, img:"chilly-paneer.png"},
{category:"Starters Veg", name:"Paneer Thawa Fry", price:340, img:"paneer-thawa-fry.png"},
{category:"Starters Veg", name:"Gobi Manchurian Dry", price:180, img:"gobi-manchurian-dry.png"},
{category:"Starters Veg", name:"Paneer Manchurian Dry", price:220, img:"paneer-manchurian-dry.png"},
{category:"Starters Veg", name:"Chilly Mushroom", price:200, img:"chilly-mushroom.png"},



{category:"Curries Veg", name:"Veg Kadai", price:225, img:"veg-kadai.png"},
{category:"Curries Veg", name:"Mix Veg Curry", price:225, img:"mix-veg-curry.png"},
{category:"Curries Veg", name:"Paneer Kadai", price:250, img:"paneer-kadai.png"},
{category:"Curries Veg", name:"Chilly Paneer Gravy", price:250, img:"chilly-paneer-gravy.png"},
{category:"Curries Veg", name:"Paneer Butter Masala", price:270, img:"paneer-butter-masala.png"},
{category:"Curries Veg", name:"Aloo Capsicum Masala", price:250, img:"aloo-capsicum-masala.png"},
{category:"Curries Veg", name:"Chilly Veg Curry", price:255, img:"chilly-veg-curry.png"},
{category:"Curries Veg", name:"Aloo Mutter Masala", price:225, img:"aloo-mutter-masala.png"},
{category:"Curries Veg", name:"Greenpeas Masala", price:225, img:"greenpeas-masala.png"},
{category:"Curries Veg", name:"Aloo Gobi Masala", price:225, img:"aloo-gobi-masala.png"},
{category:"Curries Veg", name:"Gobi Masala", price:225, img:"gobi-masala.png"},
{category:"Curries Veg", name:"Chilly Gobi Gravy", price:230, img:"chilly-gobi-gravy.png"},
{category:"Curries Veg", name:"Dhal Fry", price:200, img:"dhal-fry.png"},
{category:"Curries Veg", name:"Dhal Thadka", price:200, img:"dhal-thadka.png"},
{category:"Curries Veg", name:"Veg Chettinadu", price:225, img:"veg-chettinadu.png"},
{category:"Curries Veg", name:"Mushroom Masala", price:225, img:"mushroom-masala.png"},
{category:"Curries Veg", name:"Chilly Mushroom Gravy", price:240, img:"chilly-mushroom-gravy.png"},
{category:"Curries Veg", name:"Gobi Manchurian", price:200, img:"gobi-manchurian.png"},
{category:"Curries Veg", name:"Tomato Fry", price:180, img:"tomato-fry.png"},
{category:"Curries Veg", name:"Paneer Manchurian", price:220, img:"paneer-manchurian.png"},



{category:"Curries Sea Food", name:"Prawns Curry", price:350, img:"prawns-curry.avif"},
{category:"Curries Sea Food", name:"Prawns Varatiyathu", price:410, img:"prawns-varatiyathu.avif"},
{category:"Curries Sea Food", name:"Prawns Masala", price:350, img:"prawns-masala.png"},
{category:"Curries Sea Food", name:"Fish Curry", price:350, img:"fish-curry.jpg"},
{category:"Curries Sea Food", name:"Chilly Fish Gravy", price:350, img:"chilly-fish-gravy.jpg"},
{category:"Curries Sea Food", name:"Garlic Fish", price:350, img:"garlic-fish.jpg"},
{category:"Curries Sea Food", name:"Ginger Fish", price:350, img:"ginger-fish.png"},
{category:"Curries Sea Food", name:"Chilly Prawn Gravy", price:380, img:"chilly-prawn-gravy.jpg"},
{category:"Curries Sea Food", name:"Fish Manchurian", price:360, img:"fish-manchurian.webp"},
{category:"Curries Sea Food", name:"Vovel Meen Masala", price:320, img:"vovel-meen-masala.avif"},
{category:"Curries Sea Food", name:"Malabar Fish Curry", price:340, img:"malabar-fish-curry.jpg"},
{category:"Curries Sea Food", name:"Fish Mappas", price:410, img:"fish-mappas.jpg"},
{category:"Curries Sea Food", name:"Pal Konju", price:410, img:"pal-konju-curry.png"},
{category:"Curries Sea Food", name:"Fish Nirvana", price:430, img:"fish-nirvana.jpg"},



{category:"Curries Meat", name:"Home Style Chicken Curry", price:300, img:"home-style-chicken-curry.webp"},
{category:"Curries Meat", name:"Chicken Pepper Masala", price:300, img:"chicken-pepper-masala.jpg"},
{category:"Curries Meat", name:"Chicken Chettinadu", price:300, img:"chicken-chettinadu.webp"},
{category:"Curries Meat", name:"Chicken Kuruma", price:290, img:"chicken-kuruma.jpg"},
{category:"Curries Meat", name:"Kerala Style Chicken Curry", price:275, img:"kerala-style-chicken-curry.webp"},
{category:"Curries Meat", name:"Butter Chicken Masala", price:320, img:"butter-chicken-masala.jpg"},
{category:"Curries Meat", name:"Chicken Kadai Masala", price:300, img:"chicken-kadai-masala.jpg"},
{category:"Curries Meat", name:"Pichupota Kozhi", price:300, img:"pichupota-kozhi.jpg"},
{category:"Curries Meat", name:"Chicken Varutha Curry", price:330, img:"chicken-varutha-curry.jpg"},
{category:"Curries Meat", name:"Natukoli Curry", price:400, img:"natukoli-curry.jpg"},
{category:"Curries Meat", name:"Chilly Chicken Gravy", price:230, img:"chilly-chicken-gravy.jpg"},
{category:"Curries Meat", name:"Chilly Beef Gravy", price:380, img:"chilly-beef-gravy.jpg"},
{category:"Curries Meat", name:"Beef Curry", price:350, img:"beef-curry.png"},
{category:"Curries Meat", name:"Beef Pepper Masala", price:370, img:"beef-pepper-masala.webp"},
{category:"Curries Meat", name:"Mutton Kuruma", price:480, img:"mutton-kuruma.jpg"},
{category:"Curries Meat", name:"Mutton Chettinadu", price:480, img:"mutton-chettinadu.jpg"},
{category:"Curries Meat", name:"Mutton Pepper Masala", price:490, img:"mutton-pepper-masala.jpg"},
{category:"Curries Meat", name:"Mutton Rogan Josh", price:490, img:"mutton-rogan-josh.avif"},




{category:"Chinese & Continental", name:"Chicken Fried Rice", price:300, img:"chicken-fried-rice.webp"},
{category:"Chinese & Continental", name:"Veg Fried Rice", price:250, img:"veg-fried-rice.webp"},
{category:"Chinese & Continental", name:"Prawn Fried Rice", price:340, img:"prawn-fried-rice.jpg"},
{category:"Chinese & Continental", name:"Mixed Non Veg Fried Rice", price:380, img:"mixed-non-veg-fried-rice.avif"},
{category:"Chinese & Continental", name:"Mutton Fried Rice", price:400, img:"mutton-fried-rice.webp"},
{category:"Chinese & Continental", name:"Egg Fried Rice", price:275, img:"egg-fried-rice.jpg"},
{category:"Chinese & Continental", name:"Schezwan Chicken Fried Rice", price:325, img:"schezwan-chicken-fried-rice.png"},
{category:"Chinese & Continental", name:"Schezwan Veg Fried Rice", price:275, img:"schezwan-veg-fried-rice.jpg"},
{category:"Chinese & Continental", name:"Schezwan Prawn Fried Rice", price:360, img:"schezwan-prawn-fried-rice.jpg"},
{category:"Chinese & Continental", name:"Schez. Mix Non Veg Fried Rice", price:370, img:"schezwan-mix-non-veg-fried-rice.jpeg"},
{category:"Chinese & Continental", name:"Schezwan Mutton Fried Rice", price:390, img:"schezwan-mutton-fried-rice.jpg"},
{category:"Chinese & Continental", name:"Schezwan Egg Fried Rice", price:295, img:"schezwan-egg-fried-rice.jpeg"},
{category:"Chinese & Continental", name:"Veg Noodles", price:250, img:"veg-noodles.jpeg"},
{category:"Chinese & Continental", name:"Egg Noodles", price:275, img:"egg-noodles.jpg"},
{category:"Chinese & Continental", name:"Chicken Noodles", price:300, img:"chicken-noodles.jpg"},
{category:"Chinese & Continental", name:"Schezwan Veg Noodles", price:285, img:"schezwan-veg-noodles.avif"},
{category:"Chinese & Continental", name:"Schezwan Egg Noodles", price:300, img:"schezwan-egg-noodles.webp"},
{category:"Chinese & Continental", name:"Schezwan Chicken Noodles", price:325, img:"schezwan-chicken-noodles.webp"},
{category:"Chinese & Continental", name:"White Sauce Pasta Chicken", price:300, img:"white-sauce-pasta-chicken.webp"},
{category:"Chinese & Continental", name:"Tomato Tangy Pasta Chicken", price:300, img:"tomato-tangy-pasta-chicken.png"},
{category:"Chinese & Continental", name:"Cheese Pasta Chicken", price:330, img:"cheese-pasta-chicken.webp"},
{category:"Chinese & Continental", name:"White Sauce Prawn Pasta", price:360, img:"white-sauce-prawn-pasta.webp"},
{category:"Chinese & Continental", name:"White Sauce Veg Pasta", price:275, img:"white-sauce-veg-pasta.jpg"},
{category:"Chinese & Continental", name:"Cheese Pasta Veg", price:275, img:"cheese-pasta-veg.jpg"},
{category:"Chinese & Continental", name:"Tomato Tangy Pasta Veg", price:330, img:"tomato-tangy-pasta-veg.jpg"},



{category:"Rice", name:"Plain Rice", price:110, img:"plain-rice.png"},
{category:"Rice", name:"Jeera Rice", price:200, img:"jeera-rice.png"},
{category:"Rice", name:"Ghee Rice", price:250, img:"ghee-rice.png"},
{category:"Rice", name:"Curd Rice", price:180, img:"curd-rice.png"},
{category:"Rice", name:"Veg Pulao", price:220, img:"veg-pulao.png"},
{category:"Rice", name:"Paneer Pulao", price:220, img:"paneer-pulao.png"},
{category:"Rice", name:"Sambar Rice", price:180, img:"sambar-rice.png"},


{category:"Indian Breads", name:"Phulka (2 Pcs)", price:75, img:"phulka.png"},
{category:"Indian Breads", name:"Butter Phulka (2 Pcs)", price:90, img:"butter-phulka.png"},
{category:"Indian Breads", name:"Chappathi (2 Pcs)", price:75, img:"chappathi.png"},
{category:"Indian Breads", name:"Butter Chappathi (2 Pcs)", price:70, img:"butter-chappathi.png"},
{category:"Indian Breads", name:"Wheat Parota", price:50, img:"wheat-parota.png"},
{category:"Indian Breads", name:"Kerala Parota", price:75, img:"kerala-parota.png"},
{category:"Indian Breads", name:"Gobi Parota", price:80, img:"gobi-parota.png"},
{category:"Indian Breads", name:"Aloo Parota", price:80, img:"aloo-parota.png"},



{category:"Egg Items", name:"Egg Omelet", price:150, img:"egg-omelet.jpg"},
{category:"Egg Items", name:"Egg Podimas", price:150, img:"egg-podimas.jpg"},
{category:"Egg Items", name:"Boiled Egg (2 Nos)", price:100, img:"boiled-egg.jpg"},
{category:"Egg Items", name:"Half Boiled (2 Nos)", price:100, img:"half-boiled-egg.jpg"},
{category:"Egg Items", name:"Egg Burji", price:200, img:"egg-burji.png"},
{category:"Egg Items", name:"Egg Dosa", price:10, img:"egg-dosa.webp"},
{category:"Egg Items", name:"Egg Masala", price:200, img:"egg-masala.jpg"},
{category:"Egg Items", name:"Egg Masala Dosa", price:95, img:"egg-masala-dosa.jpg"},
{category:"Egg Items", name:"Egg Pepper Fry", price:200, img:"egg-pepper-fry.jpg"},
{category:"Egg Items", name:"Egg Roast", price:200, img:"egg-roast.jpg"},
{category:"Egg Items", name:"Poached Egg Masala", price:200, img:"poached-egg-masala.jpg"},


{category:"Desserts", name:"Carrot Halwa", price:100, img:"carrot-halwa.png"},
{category:"Desserts", name:"Rasagula (2 Pcs)", price:110, img:"rasagula.avif"},
{category:"Desserts", name:"Gulab Jam (2 Pcs)", price:120, img:"gulab-jamun.avif"},
{category:"Desserts", name:"Chocolate Mousse", price:120, img:"chocolate-mousse.jpg"},
{category:"Desserts", name:"Ice Creams (Single Scoop)", price:99, img:"ice-cream.jpg"},
{category:"Desserts", name:"Vanilla Pannacotta", price:170, img:"vanilla-pannacotta.png"},
{category:"Desserts", name:"Shahi Tukda", price:130, img:"shahi-tukda.jpg"},



{category:"Beverage", name:"Tea", price:50, img:"tea.jpg"},
{category:"Beverage", name:"Ginger Tea", price:55, img:"ginger-tea.webp"},
{category:"Beverage", name:"Elachi Tea", price:60, img:"elachi-tea.jpg"},
{category:"Beverage", name:"Masala Tea", price:60, img:"masala-tea.webp"},
{category:"Beverage", name:"Black Tea", price:30, img:"black-tea.avif"},
{category:"Beverage", name:"Lemon Tea", price:50, img:"lemon-tea.jpg"},
{category:"Beverage", name:"Mint Tea", price:50, img:"mint-tea.jpg"},
{category:"Beverage", name:"Coffee", price:50, img:"coffee.jpg"},
{category:"Beverage", name:"Black Coffee", price:30, img:"black-coffee.png"},
{category:"Beverage", name:"Cold Coffee", price:100, img:"cold-coffee.jpg"},
{category:"Beverage", name:"Boost", price:65, img:"boost.avif"},
{category:"Beverage", name:"Horlicks", price:65, img:"horlicks.webp"},
{category:"Beverage", name:"Hot Milk", price:40, img:"hot-milk.png"},
{category:"Beverage", name:"Cold Milk", price:40, img:"cold-milk.jpg"},

{category:"Beverage", name:"Milk (With Pepper & Turmeric)", price:60, img:"pepper-turmeric-milk.jpg"},
{category:"Beverage", name:"Hot Chocolate", price:100, img:"hot-chocolate.jpg"},
{category:"Beverage", name:"Butter Milk", price:80, img:"butter-milk.jpg"},
{category:"Beverage", name:"Lassi", price:100, img:"lassi.jpg"},
{category:"Beverage", name:"Fresh Fruit Juice", price:160, img:"fresh-fruit-juice.jpg"},
{category:"Beverage", name:"Milk Shakes", price:150, img:"milk-shakes.jpg"},
{category:"Beverage", name:"Lemon Soda", price:120, img:"lemon-soda.webp"},
{category:"Beverage", name:"Fresh Lime Juice", price:80, img:"fresh-lime-juice.avif"},
{category:"Beverage", name:"Fresh Mint Lime Juice", price:90, img:"fresh-mint-lime-juice.jpg"},
{category:"Beverage", name:"Mojitos", price:150, img:"mojitos.jpg"},
{category:"Beverage", name:"Soft Drinks", price:90, img:"soft-drinks.jpg"},
{category:"Beverage", name:"Fresh Fruit Smoothies", price:210, img:"fresh-fruit-smoothies.jpg"},
];
